name: allowance_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
# Firebase
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  cloud_firestore: ^2.2.2
# Get version number, build number, app name etc.
  package_info: ^2.0.2
# Shared Preference
  shared_preferences: ^2.0.5
# iOS icons
  cupertino_icons: ^1.0.3
  flutter_launcher_icons: ^0.9.0
# Gradient app bar
  gradient_app_bar: ^0.1.3
# Floating Button
  flutter_speed_dial: ^3.0.5
# Bar indicator
  percent_indicator: ^3.0.1
# isNotBlank
  quiver: ^3.0.1
# ViewModel
  scoped_model: ^2.0.0-nullsafety.0
  flutter_riverpod: ^0.14.0+3
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4
# Graph
  fl_chart: ^0.36.1
# Admob
  admob_flutter: ^2.0.0-nullsafety.0

# Localize
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true

flutter:
  # Localize
  generate: true

  uses-material-design: true
  fonts:
    - family: defaultFont
      fonts:
        - asset: fonts/yasashisagothic.otf
    - family: enAccent
      fonts:
        - asset: fonts/Pacifico.ttf
    - family: jaAccent
      fonts:
        - asset: fonts/RiiPopkkR.otf
